### ISSUE TITLE
TypeError: Cannot read property 'UUID' of null

### ISSUE THREAD

**Issue by elbogi** [ptz0n/homebridge-verisure#2]
```
[Verisure] Initializing platform accessory 'undefined (Kitchen)'...
/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:128
    if (existing.UUID === service.UUID) {
                                 ^
TypeError: Cannot read property 'UUID' of null
```

In my overview, "kitchen" is the temperature sensor that's controlled by Verisure.
So what I can gather, the plugin is unable to read the UUID of this component. It fails with this, so I don't know if it can read any of the smart plugs for instance.

**Comment by ptz0n** [comment]
Looks like an early fail in registering the accessories. What kind of device is that?

**Comment by elbogi** [comment]
Hey.
Look at this picture from the Verisure page. Hope it helps.
<img width="456" alt="skjermbilde 2017-01-24 kl 08 53 58" src="https://cloud.githubusercontent.com/assets/1804857/22238707/4ab918c4-e213-11e6-95c0-4fb4ed6afdb7.png">

**Comment by ptz0n** [comment]
Oh, the siren, nice!

Could you output of your installation `overview` using [this module](https://github.com/ptz0n/node-verisure)?

__OBS! Without disclosing any location or serial number details.__

**Comment by ptz0n** [comment]
Hopefully fixed in version [`1.2.0`](https://github.com/ptz0n/homebridge-verisure/commit/1a44391df3789cca4806caf4e1bbaddc38d6d59b) 👍 

`npm install -g homebridge-verisure`

**Comment by elbogi** [comment]
TOKEN: 706ookqsoutlcc5hfid951pocd
INSTALLATIONS: [ { giid: '14123794580',
    firmwareVersion: 25230,
    routingGroup: 'NO',
    shard: 7,
    locale: 'no_NO',
    signalFilterId: 1,
    deleted: false,
    cid: '00215512',
    street: 'street',
    streetNo1: '',
    streetNo2: '',
    alias: 'xxxx' } ]
OVERVIEW: { armState: 
   { statusType: 'DISARMED',
     date: '2016-12-25T18:01:00.000Z',
     name: 'Name',
     changedVia: 'CODE' },
  armstateCompatible: true,
  controlPlugs: 
   [ { deviceId: '33998643',
       deviceLabel: 'xxxx',
       area: 'Spisestue',
       profile: 'LIGHT',
       currentState: 'OFF',
       pendingState: 'NONE' },
     { deviceId: '33998642',
       deviceLabel: 'xxxx',
       area: 'Lampe',
       profile: 'LIGHT',
       currentState: 'OFF',
       pendingState: 'NONE' } ],
  smartPlugs: 
   [ { icon: 'LIGHT',
       isHazardous: false,
       deviceLabel: 'xxxx',
       area: 'Spisestue',
       currentState: 'OFF',
       pendingState: 'NONE' },
     { icon: 'LIGHT',
       isHazardous: false,
       deviceLabel: 'xxxx',
       area: 'Lampe',
       currentState: 'OFF',
       pendingState: 'NONE' } ],
  doorLockStatusList: [],
  totalSmsCount: 49,
  climateValues: 
   [ { deviceLabel: 'xxxx',
       deviceArea: 'Kitchen',
       deviceType: 'SIREN1',
       temperature: 19.5,
       time: '2017-01-24T08:01:44.000Z' } ],
  installationErrorList: [],
  pendingChanges: 0,
  ethernetModeActive: true,
  ethernetConnectedNow: true,
  heatPumps: [],
  smartCameras: [],
  latestEthernetStatus: 
   { latestEthernetTestResult: true,
     testDate: '2017-01-23T14:30:15.000Z',
     protectedArea: 'TEKNISKT ROM',
     deviceLabel: 'xxxx' },
  customerImageCameras: [],
  batteryProcess: { active: false },
  eventCounts: [],
  doorWindow: 
   { reportState: true,
     doorWindowDevice: [ [Object], [Object], [Object] ] } }

**Comment by ptz0n** [comment]
There we go: `SIREN1 `

**Comment by elbogi** [comment]
I still get the same error except this time the device is identified as 'SIREN1'.

**Comment by ptz0n** [comment]
Ok, then I need to debug some more tonight. Support for `controlPlugs` as an added bonus? 💃

**Comment by ptz0n** [comment]
Fixed in https://github.com/ptz0n/homebridge-verisure/commit/a92dee28138e9890c64a562425e337fe3184de26.
